// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-dashboard/internal/sdk/models/shared"
	"net/http"
)

type CreateDashboardResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The created dashboard
	Dashboard *shared.Dashboard
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *CreateDashboardResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateDashboardResponse) GetDashboard() *shared.Dashboard {
	if c == nil {
		return nil
	}
	return c.Dashboard
}

func (c *CreateDashboardResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateDashboardResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}
