// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-dashboard/internal/sdk/models/shared"
	"net/http"
)

type DeleteDashboardRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteDashboardRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteDashboardResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The deleted dashboard
	Dashboard *shared.Dashboard
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DeleteDashboardResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteDashboardResponse) GetDashboard() *shared.Dashboard {
	if d == nil {
		return nil
	}
	return d.Dashboard
}

func (d *DeleteDashboardResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteDashboardResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
