// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-dashboard/internal/sdk/models/shared"
	"net/http"
)

type DeleteInsightRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteInsightRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteInsightResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The deleted insight
	Insight *shared.Insight
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DeleteInsightResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteInsightResponse) GetInsight() *shared.Insight {
	if d == nil {
		return nil
	}
	return d.Insight
}

func (d *DeleteInsightResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteInsightResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
