// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-dashboard/internal/sdk/models/shared"
	"net/http"
)

type GetDashboardRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetDashboardRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetDashboardResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The dashboard with the passed ID
	Dashboard *shared.Dashboard
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetDashboardResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetDashboardResponse) GetDashboard() *shared.Dashboard {
	if g == nil {
		return nil
	}
	return g.Dashboard
}

func (g *GetDashboardResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetDashboardResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
