// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-dashboard/internal/sdk/models/shared"
	"net/http"
)

type GetInsightRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetInsightRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetInsightResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The insight with the passed ID
	Insight *shared.Insight
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetInsightResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetInsightResponse) GetInsight() *shared.Insight {
	if g == nil {
		return nil
	}
	return g.Insight
}

func (g *GetInsightResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetInsightResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
