// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-dashboard/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-dashboard/internal/sdk/models/shared"
	"net/http"
	"time"
)

type ListInsightsRequest struct {
	// Filter to resources the given user id may view (owner, shared, org-wide or legacy).
	AccessibleTo  *string    `queryParam:"style=form,explode=true,name=accessible_to"`
	CreatedAfter  *time.Time `queryParam:"style=form,explode=true,name=created_after"`
	CreatedBefore *time.Time `queryParam:"style=form,explode=true,name=created_before"`
	// Filter by the id of the creating user.
	CreatedBy *string `queryParam:"style=form,explode=true,name=created_by"`
	// Maximum results to return (max 200). Omit to return all matching results (pagination is opt-in).
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Number of results to skip, for pagination. Use with limit (page N = offset N*limit).
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
	// Sort direction. Defaults to ascending (preserving the pre-migration order).
	Order *shared.Order `default:"asc" queryParam:"style=form,explode=true,name=order"`
	// Filter to resources owned by any of the given user ids.
	Owner []string `queryParam:"style=form,explode=true,name=owner"`
	// Free-text search over name/title and description (case-insensitive substring).
	Q *string `queryParam:"style=form,explode=true,name=q"`
	// Filter to resources shared with any of the given user ids.
	SharedWith []string `queryParam:"style=form,explode=true,name=shared_with"`
	// Field to sort by. `name` and `title` are aliases for the resource's display name and are normalised per resource: dashboards sort by `title` and insights by `name`, whichever of the two values is sent. String sorts are case-insensitive.
	Sort *shared.Sort `default:"updated_at" queryParam:"style=form,explode=true,name=sort"`
	// Filter by one or more tags (see tags_match for any/all semantics).
	Tags []string `queryParam:"style=form,explode=true,name=tags"`
	// Whether a result must match any (default) or all of the given tags.
	TagsMatch     *shared.TagsMatch `default:"any" queryParam:"style=form,explode=true,name=tags_match"`
	UpdatedAfter  *time.Time        `queryParam:"style=form,explode=true,name=updated_after"`
	UpdatedBefore *time.Time        `queryParam:"style=form,explode=true,name=updated_before"`
	// Filter insights by one or more visualisation ids.
	VisualisationID []shared.VisualisationID `queryParam:"style=form,explode=true,name=visualisation_id"`
}

func (l ListInsightsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListInsightsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListInsightsRequest) GetAccessibleTo() *string {
	if l == nil {
		return nil
	}
	return l.AccessibleTo
}

func (l *ListInsightsRequest) GetCreatedAfter() *time.Time {
	if l == nil {
		return nil
	}
	return l.CreatedAfter
}

func (l *ListInsightsRequest) GetCreatedBefore() *time.Time {
	if l == nil {
		return nil
	}
	return l.CreatedBefore
}

func (l *ListInsightsRequest) GetCreatedBy() *string {
	if l == nil {
		return nil
	}
	return l.CreatedBy
}

func (l *ListInsightsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListInsightsRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListInsightsRequest) GetOrder() *shared.Order {
	if l == nil {
		return nil
	}
	return l.Order
}

func (l *ListInsightsRequest) GetOwner() []string {
	if l == nil {
		return nil
	}
	return l.Owner
}

func (l *ListInsightsRequest) GetQ() *string {
	if l == nil {
		return nil
	}
	return l.Q
}

func (l *ListInsightsRequest) GetSharedWith() []string {
	if l == nil {
		return nil
	}
	return l.SharedWith
}

func (l *ListInsightsRequest) GetSort() *shared.Sort {
	if l == nil {
		return nil
	}
	return l.Sort
}

func (l *ListInsightsRequest) GetTags() []string {
	if l == nil {
		return nil
	}
	return l.Tags
}

func (l *ListInsightsRequest) GetTagsMatch() *shared.TagsMatch {
	if l == nil {
		return nil
	}
	return l.TagsMatch
}

func (l *ListInsightsRequest) GetUpdatedAfter() *time.Time {
	if l == nil {
		return nil
	}
	return l.UpdatedAfter
}

func (l *ListInsightsRequest) GetUpdatedBefore() *time.Time {
	if l == nil {
		return nil
	}
	return l.UpdatedBefore
}

func (l *ListInsightsRequest) GetVisualisationID() []shared.VisualisationID {
	if l == nil {
		return nil
	}
	return l.VisualisationID
}

// ListInsightsResponseBody - List of insights available to the user
type ListInsightsResponseBody struct {
	// Offset-based pagination metadata for list responses
	Pagination shared.Pagination `json:"pagination"`
	Results    []shared.Insight  `json:"results"`
}

func (l *ListInsightsResponseBody) GetPagination() shared.Pagination {
	if l == nil {
		return shared.Pagination{}
	}
	return l.Pagination
}

func (l *ListInsightsResponseBody) GetResults() []shared.Insight {
	if l == nil {
		return []shared.Insight{}
	}
	return l.Results
}

type ListInsightsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of insights available to the user
	Object *ListInsightsResponseBody
}

func (l *ListInsightsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListInsightsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListInsightsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListInsightsResponse) GetObject() *ListInsightsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
