// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

// ListInsightTagsResponseBody - Distinct tags used by insights in the organization
type ListInsightTagsResponseBody struct {
	Results []string `json:"results,omitempty"`
}

func (l *ListInsightTagsResponseBody) GetResults() []string {
	if l == nil {
		return nil
	}
	return l.Results
}

type ListInsightTagsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Distinct tags used by insights in the organization
	Object *ListInsightTagsResponseBody
}

func (l *ListInsightTagsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListInsightTagsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListInsightTagsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListInsightTagsResponse) GetObject() *ListInsightTagsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
