// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-dashboard/internal/sdk/models/shared"
	"net/http"
)

// ListDashboardsResponseBody - List of dashboards available to the user
type ListDashboardsResponseBody struct {
	Results []shared.Dashboard `json:"results,omitempty"`
}

func (l *ListDashboardsResponseBody) GetResults() []shared.Dashboard {
	if l == nil {
		return nil
	}
	return l.Results
}

type ListDashboardsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of dashboards available to the user
	Object *ListDashboardsResponseBody
}

func (l *ListDashboardsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListDashboardsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListDashboardsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListDashboardsResponse) GetObject() *ListDashboardsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
