// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-dashboard/internal/sdk/models/shared"
	"net/http"
)

// ListAvailableExamplesResponseBody - List of available exampless for visualisations to configure new dashboard tiles
type ListAvailableExamplesResponseBody struct {
	Results []shared.Example `json:"results,omitempty"`
}

func (l *ListAvailableExamplesResponseBody) GetResults() []shared.Example {
	if l == nil {
		return nil
	}
	return l.Results
}

type ListAvailableExamplesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of available exampless for visualisations to configure new dashboard tiles
	Object *ListAvailableExamplesResponseBody
}

func (l *ListAvailableExamplesResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListAvailableExamplesResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListAvailableExamplesResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListAvailableExamplesResponse) GetObject() *ListAvailableExamplesResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
