// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-dashboard/internal/sdk/models/shared"
	"net/http"
)

type PatchInsightRequest struct {
	// The insight fields to update
	InsightPatch *shared.InsightPatch `request:"mediaType=application/json"`
	ID           string               `pathParam:"style=simple,explode=false,name=id"`
}

func (p *PatchInsightRequest) GetInsightPatch() *shared.InsightPatch {
	if p == nil {
		return nil
	}
	return p.InsightPatch
}

func (p *PatchInsightRequest) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

type PatchInsightResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The updated insight
	Insight *shared.Insight
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (p *PatchInsightResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PatchInsightResponse) GetInsight() *shared.Insight {
	if p == nil {
		return nil
	}
	return p.Insight
}

func (p *PatchInsightResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PatchInsightResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}
