// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-dashboard/internal/sdk/models/shared"
	"net/http"
)

type PatchDashboardRequest struct {
	// The dashboard fields to update
	DashboardPatch *shared.DashboardPatch `request:"mediaType=application/json"`
	ID             string                 `pathParam:"style=simple,explode=false,name=id"`
}

func (p *PatchDashboardRequest) GetDashboardPatch() *shared.DashboardPatch {
	if p == nil {
		return nil
	}
	return p.DashboardPatch
}

func (p *PatchDashboardRequest) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

type PatchDashboardResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The updated dashboard
	Dashboard *shared.Dashboard
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (p *PatchDashboardResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PatchDashboardResponse) GetDashboard() *shared.Dashboard {
	if p == nil {
		return nil
	}
	return p.Dashboard
}

func (p *PatchDashboardResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PatchDashboardResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}
