// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-dashboard/internal/sdk/models/shared"
	"net/http"
)

type PutInsightRequest struct {
	// The updated insight
	Insight *shared.InsightInput `request:"mediaType=application/json"`
	ID      string               `pathParam:"style=simple,explode=false,name=id"`
}

func (p *PutInsightRequest) GetInsight() *shared.InsightInput {
	if p == nil {
		return nil
	}
	return p.Insight
}

func (p *PutInsightRequest) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

type PutInsightResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The insight with the passed ID
	Insight *shared.Insight
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (p *PutInsightResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PutInsightResponse) GetInsight() *shared.Insight {
	if p == nil {
		return nil
	}
	return p.Insight
}

func (p *PutInsightResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PutInsightResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}
