// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// Dashboard - Adashboard configuration with tiles
type Dashboard struct {
	// Unique identifier for dashboard
	ID    *string `json:"id,omitempty"`
	Tiles any     `json:"tiles"`
	Title string  `json:"title"`
}

func (d *Dashboard) GetID() *string {
	if d == nil {
		return nil
	}
	return d.ID
}

func (d *Dashboard) GetTiles() any {
	if d == nil {
		return nil
	}
	return d.Tiles
}

func (d *Dashboard) GetTitle() string {
	if d == nil {
		return ""
	}
	return d.Title
}
