// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// DashboardPatch - Fields that can be partially updated on a dashboard
type DashboardPatch struct {
	// Optional organization-wide grant. When set, every user in the resource's organization
	// is granted this permission level. `null` (or omitted) means the resource is not shared
	// org-wide.
	//
	OrgAccess *OrgAccess `json:"org_access,omitempty"`
	// Replaces the entire list of owner user ids. Must keep at least one owner (else 400).
	// Omit to leave owners unchanged.
	//
	Owners []string `json:"owners,omitempty"`
	// Replaces the entire list of per-user grants — any existing grant not included is removed.
	// Omit to leave sharing unchanged; send an empty array to revoke all per-user grants.
	//
	SharedWith []ShareGrant    `json:"shared_with,omitempty"`
	Tiles      []DashboardTile `json:"tiles,omitempty"`
	Title      *string         `json:"title,omitempty"`
}

func (d *DashboardPatch) GetOrgAccess() *OrgAccess {
	if d == nil {
		return nil
	}
	return d.OrgAccess
}

func (d *DashboardPatch) GetOwners() []string {
	if d == nil {
		return nil
	}
	return d.Owners
}

func (d *DashboardPatch) GetSharedWith() []ShareGrant {
	if d == nil {
		return nil
	}
	return d.SharedWith
}

func (d *DashboardPatch) GetTiles() []DashboardTile {
	if d == nil {
		return nil
	}
	return d.Tiles
}

func (d *DashboardPatch) GetTitle() *string {
	if d == nil {
		return nil
	}
	return d.Title
}
