// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Coordinates struct {
}

// DashboardTile - A positioned tile on a dashboard canvas. A tile references a saved insight via
// `insight_id`. Inline `visualisation_id`/`visualisation_config` remain supported for
// backwards compatibility (ad-hoc tiles that are not backed by a shared insight).
type DashboardTile struct {
	Coordinates *Coordinates `json:"coordinates,omitempty"`
	// Unique identifier for a tile in a dashboard
	ID *string `json:"id,omitempty"`
	// Unique identifier for an insight (a saved chart / visualisation)
	InsightID           *string              `json:"insight_id,omitempty"`
	Title               *string              `json:"title,omitempty"`
	VisualisationConfig *VisualisationConfig `json:"visualisation_config,omitempty"`
	// Unique identifier for a Visualisation
	VisualisationID *VisualisationID `json:"visualisation_id,omitempty"`
}

func (d *DashboardTile) GetCoordinates() *Coordinates {
	if d == nil {
		return nil
	}
	return d.Coordinates
}

func (d *DashboardTile) GetID() *string {
	if d == nil {
		return nil
	}
	return d.ID
}

func (d *DashboardTile) GetInsightID() *string {
	if d == nil {
		return nil
	}
	return d.InsightID
}

func (d *DashboardTile) GetTitle() *string {
	if d == nil {
		return nil
	}
	return d.Title
}

func (d *DashboardTile) GetVisualisationConfig() *VisualisationConfig {
	if d == nil {
		return nil
	}
	return d.VisualisationConfig
}

func (d *DashboardTile) GetVisualisationID() *VisualisationID {
	if d == nil {
		return nil
	}
	return d.VisualisationID
}
