// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// DashboardInput - A dashboard configuration. A dashboard is a canvas whose tiles arrange and
// position insights (saved charts). Tiles may reference an insight by `insight_id`
// or, for backwards compatibility, embed a visualisation inline.
type DashboardInput struct {
	// Unique identifier for dashboard
	ID *string `json:"id,omitempty"`
	// Optional organization-wide grant. When set, every user in the resource's organization
	// is granted this permission level. `null` (or omitted) means the resource is not shared
	// org-wide.
	//
	OrgAccess *OrgAccess `json:"org_access,omitempty"`
	// User ids with full control over the resource (view, edit, delete and manage sharing).
	// The creator is always an owner. There must always be at least one owner.
	//
	Owners []string `json:"owners,omitempty"`
	// Per-user sharing grants
	SharedWith []ShareGrant    `json:"shared_with,omitempty"`
	Tiles      []DashboardTile `json:"tiles"`
	Title      string          `json:"title"`
}

func (d *DashboardInput) GetID() *string {
	if d == nil {
		return nil
	}
	return d.ID
}

func (d *DashboardInput) GetOrgAccess() *OrgAccess {
	if d == nil {
		return nil
	}
	return d.OrgAccess
}

func (d *DashboardInput) GetOwners() []string {
	if d == nil {
		return nil
	}
	return d.Owners
}

func (d *DashboardInput) GetSharedWith() []ShareGrant {
	if d == nil {
		return nil
	}
	return d.SharedWith
}

func (d *DashboardInput) GetTiles() []DashboardTile {
	if d == nil {
		return []DashboardTile{}
	}
	return d.Tiles
}

func (d *DashboardInput) GetTitle() string {
	if d == nil {
		return ""
	}
	return d.Title
}
