// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Example struct {
	// Unique identifier for a visualisation examples for tiles in a dashboard
	ID    *string        `json:"id,omitempty"`
	Query *DatalakeQuery `json:"query,omitempty"`
	Title *string        `json:"title,omitempty"`
	// Unique identifier for a Visualisation
	Visualisation *VisualisationID `json:"visualisation,omitempty"`
}

func (e *Example) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *Example) GetQuery() *DatalakeQuery {
	if e == nil {
		return nil
	}
	return e.Query
}

func (e *Example) GetTitle() *string {
	if e == nil {
		return nil
	}
	return e.Title
}

func (e *Example) GetVisualisation() *VisualisationID {
	if e == nil {
		return nil
	}
	return e.Visualisation
}
