// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// InsightPatch - Fields that can be partially updated on an insight
type InsightPatch struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
	// Optional organization-wide grant. When set, every user in the resource's organization
	// is granted this permission level. `null` (or omitted) means the resource is not shared
	// org-wide.
	//
	OrgAccess *OrgAccess `json:"org_access,omitempty"`
	// Replaces the entire list of owner user ids. Must keep at least one owner (else 400).
	// Omit to leave owners unchanged.
	//
	Owners []string `json:"owners,omitempty"`
	// Replaces the entire list of per-user grants — any existing grant not included is removed.
	// Omit to leave sharing unchanged; send an empty array to revoke all per-user grants.
	//
	SharedWith []ShareGrant `json:"shared_with,omitempty"`
	// Free-form labels for grouping and filtering insights
	Tags                []string             `json:"tags,omitempty"`
	VisualisationConfig *VisualisationConfig `json:"visualisation_config,omitempty"`
	// Unique identifier for a Visualisation
	VisualisationID *VisualisationID `json:"visualisation_id,omitempty"`
}

func (i *InsightPatch) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *InsightPatch) GetName() *string {
	if i == nil {
		return nil
	}
	return i.Name
}

func (i *InsightPatch) GetOrgAccess() *OrgAccess {
	if i == nil {
		return nil
	}
	return i.OrgAccess
}

func (i *InsightPatch) GetOwners() []string {
	if i == nil {
		return nil
	}
	return i.Owners
}

func (i *InsightPatch) GetSharedWith() []ShareGrant {
	if i == nil {
		return nil
	}
	return i.SharedWith
}

func (i *InsightPatch) GetTags() []string {
	if i == nil {
		return nil
	}
	return i.Tags
}

func (i *InsightPatch) GetVisualisationConfig() *VisualisationConfig {
	if i == nil {
		return nil
	}
	return i.VisualisationConfig
}

func (i *InsightPatch) GetVisualisationID() *VisualisationID {
	if i == nil {
		return nil
	}
	return i.VisualisationID
}
