// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-dashboard/internal/sdk/internal/utils"
	"time"
)

// Insight - An insight is a saved, reusable chart definition (a visualisation plus its query/options).
// Insights exist independently of dashboards: they can be created, shared and edited on their
// own, and referenced by one or more dashboard tiles via `insight_id`.
type Insight struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// Id of the user who created the resource
	CreatedBy   *string `json:"created_by,omitempty"`
	Description *string `json:"description,omitempty"`
	// Unique identifier for an insight (a saved chart / visualisation)
	ID *string `json:"id,omitempty"`
	// Human readable name of the insight
	Name string `json:"name"`
	// Optional organization-wide grant. When set, every user in the resource's organization
	// is granted this permission level. `null` (or omitted) means the resource is not shared
	// org-wide.
	//
	OrgAccess *OrgAccess `json:"org_access,omitempty"`
	// Id of the organisation that owns the resource. Set at creation time and immutable.
	OwnerOrgID *string `json:"owner_org_id,omitempty"`
	// User ids with full control over the resource (view, edit, delete and manage sharing).
	// The creator is always an owner. There must always be at least one owner.
	//
	Owners []string `json:"owners,omitempty"`
	// Per-user sharing grants
	SharedWith []ShareGrant `json:"shared_with,omitempty"`
	// Free-form labels for grouping and filtering insights
	Tags      []string   `json:"tags,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// Id of the user who last updated the resource
	UpdatedBy           *string              `json:"updated_by,omitempty"`
	VisualisationConfig *VisualisationConfig `json:"visualisation_config,omitempty"`
	// Unique identifier for a Visualisation
	VisualisationID VisualisationID `json:"visualisation_id"`
}

func (i Insight) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *Insight) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *Insight) GetCreatedAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.CreatedAt
}

func (i *Insight) GetCreatedBy() *string {
	if i == nil {
		return nil
	}
	return i.CreatedBy
}

func (i *Insight) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *Insight) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *Insight) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *Insight) GetOrgAccess() *OrgAccess {
	if i == nil {
		return nil
	}
	return i.OrgAccess
}

func (i *Insight) GetOwnerOrgID() *string {
	if i == nil {
		return nil
	}
	return i.OwnerOrgID
}

func (i *Insight) GetOwners() []string {
	if i == nil {
		return nil
	}
	return i.Owners
}

func (i *Insight) GetSharedWith() []ShareGrant {
	if i == nil {
		return nil
	}
	return i.SharedWith
}

func (i *Insight) GetTags() []string {
	if i == nil {
		return nil
	}
	return i.Tags
}

func (i *Insight) GetUpdatedAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.UpdatedAt
}

func (i *Insight) GetUpdatedBy() *string {
	if i == nil {
		return nil
	}
	return i.UpdatedBy
}

func (i *Insight) GetVisualisationConfig() *VisualisationConfig {
	if i == nil {
		return nil
	}
	return i.VisualisationConfig
}

func (i *Insight) GetVisualisationID() VisualisationID {
	if i == nil {
		return VisualisationID("")
	}
	return i.VisualisationID
}
