// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// InsightInput - An insight is a saved, reusable chart definition (a visualisation plus its query/options).
// Insights exist independently of dashboards: they can be created, shared and edited on their
// own, and referenced by one or more dashboard tiles via `insight_id`.
type InsightInput struct {
	Description *string `json:"description,omitempty"`
	// Unique identifier for an insight (a saved chart / visualisation)
	ID *string `json:"id,omitempty"`
	// Human readable name of the insight
	Name string `json:"name"`
	// Optional organization-wide grant. When set, every user in the resource's organization
	// is granted this permission level. `null` (or omitted) means the resource is not shared
	// org-wide.
	//
	OrgAccess *OrgAccess `json:"org_access,omitempty"`
	// User ids with full control over the resource (view, edit, delete and manage sharing).
	// The creator is always an owner. There must always be at least one owner.
	//
	Owners []string `json:"owners,omitempty"`
	// Per-user sharing grants
	SharedWith []ShareGrant `json:"shared_with,omitempty"`
	// Free-form labels for grouping and filtering insights
	Tags                []string             `json:"tags,omitempty"`
	VisualisationConfig *VisualisationConfig `json:"visualisation_config,omitempty"`
	// Unique identifier for a Visualisation
	VisualisationID VisualisationID `json:"visualisation_id"`
}

func (i *InsightInput) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *InsightInput) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *InsightInput) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *InsightInput) GetOrgAccess() *OrgAccess {
	if i == nil {
		return nil
	}
	return i.OrgAccess
}

func (i *InsightInput) GetOwners() []string {
	if i == nil {
		return nil
	}
	return i.Owners
}

func (i *InsightInput) GetSharedWith() []ShareGrant {
	if i == nil {
		return nil
	}
	return i.SharedWith
}

func (i *InsightInput) GetTags() []string {
	if i == nil {
		return nil
	}
	return i.Tags
}

func (i *InsightInput) GetVisualisationConfig() *VisualisationConfig {
	if i == nil {
		return nil
	}
	return i.VisualisationConfig
}

func (i *InsightInput) GetVisualisationID() VisualisationID {
	if i == nil {
		return VisualisationID("")
	}
	return i.VisualisationID
}
