// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-dashboard/internal/sdk/internal/utils"
)

type One string

const (
	OneView One = "view"
	OneEdit One = "edit"
)

func (e One) ToPointer() *One {
	return &e
}
func (e *One) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "view":
		fallthrough
	case "edit":
		*e = One(v)
		return nil
	default:
		return fmt.Errorf("invalid value for One: %v", v)
	}
}

type OrgAccessType string

const (
	OrgAccessTypeOne OrgAccessType = "1"
	OrgAccessTypeAny OrgAccessType = "any"
)

// OrgAccess - Optional organization-wide grant. When set, every user in the resource's organization
// is granted this permission level. `null` (or omitted) means the resource is not shared
// org-wide.
type OrgAccess struct {
	One *One `queryParam:"inline" union:"member"`
	Any any  `queryParam:"inline" union:"member"`

	Type OrgAccessType
}

func CreateOrgAccessOne(one One) OrgAccess {
	typ := OrgAccessTypeOne

	return OrgAccess{
		One:  &one,
		Type: typ,
	}
}

func CreateOrgAccessAny(anyT any) OrgAccess {
	typ := OrgAccessTypeAny

	return OrgAccess{
		Any:  anyT,
		Type: typ,
	}
}

func (u *OrgAccess) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var one One = One("")
	if err := utils.UnmarshalJSON(data, &one, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  OrgAccessTypeOne,
			Value: &one,
		})
	}

	var anyVar any = nil
	if err := utils.UnmarshalJSON(data, &anyVar, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  OrgAccessTypeAny,
			Value: anyVar,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for OrgAccess", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for OrgAccess", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(OrgAccessType)
	switch best.Type {
	case OrgAccessTypeOne:
		u.One = best.Value.(*One)
		return nil
	case OrgAccessTypeAny:
		u.Any = best.Value.(any)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for OrgAccess", string(data))
}

func (u OrgAccess) MarshalJSON() ([]byte, error) {
	if u.One != nil {
		return utils.MarshalJSON(u.One, "", true)
	}

	if u.Any != nil {
		return utils.MarshalJSON(u.Any, "", true)
	}

	return nil, errors.New("could not marshal union type OrgAccess: all fields are null")
}
