// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// Pagination - Offset-based pagination metadata for list responses
type Pagination struct {
	// Whether more results exist beyond this page
	HasMore bool `json:"has_more"`
	// Page size used for this response
	Limit int64 `json:"limit"`
	// Number of results skipped before this page
	Offset int64 `json:"offset"`
	// Total number of results matching the query (ignoring limit/offset)
	Total int64 `json:"total"`
}

func (p *Pagination) GetHasMore() bool {
	if p == nil {
		return false
	}
	return p.HasMore
}

func (p *Pagination) GetLimit() int64 {
	if p == nil {
		return 0
	}
	return p.Limit
}

func (p *Pagination) GetOffset() int64 {
	if p == nil {
		return 0
	}
	return p.Offset
}

func (p *Pagination) GetTotal() int64 {
	if p == nil {
		return 0
	}
	return p.Total
}
