// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ShareGrant - Grants a single user a permission level on a resource
type ShareGrant struct {
	// Permission level granted to a user (or the whole organization) on a shared resource.
	// `view` allows read-only access; `edit` additionally allows updating the content.
	// Full control (delete and managing sharing) is reserved for owners.
	//
	Permission SharePermission `json:"permission"`
	// The id of the user the resource is shared with
	UserID string `json:"user_id"`
}

func (s *ShareGrant) GetPermission() SharePermission {
	if s == nil {
		return SharePermission("")
	}
	return s.Permission
}

func (s *ShareGrant) GetUserID() string {
	if s == nil {
		return ""
	}
	return s.UserID
}
