// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// SharePermission - Permission level granted to a user (or the whole organization) on a shared resource.
// `view` allows read-only access; `edit` additionally allows updating the content.
// Full control (delete and managing sharing) is reserved for owners.
type SharePermission string

const (
	SharePermissionView SharePermission = "view"
	SharePermissionEdit SharePermission = "edit"
)

func (e SharePermission) ToPointer() *SharePermission {
	return &e
}
func (e *SharePermission) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "view":
		fallthrough
	case "edit":
		*e = SharePermission(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SharePermission: %v", v)
	}
}
