// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type TagsMatch string

const (
	TagsMatchAny TagsMatch = "any"
	TagsMatchAll TagsMatch = "all"
)

func (e TagsMatch) ToPointer() *TagsMatch {
	return &e
}
func (e *TagsMatch) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "any":
		fallthrough
	case "all":
		*e = TagsMatch(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TagsMatch: %v", v)
	}
}
