// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-dashboard/internal/sdk/internal/utils"
)

type TimechartVisualisationConfig struct {
	Options map[string]any `json:"options,omitempty"`
	Query   *DatalakeQuery `json:"query,omitempty"`
}

func (t TimechartVisualisationConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TimechartVisualisationConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TimechartVisualisationConfig) GetOptions() map[string]any {
	if t == nil {
		return nil
	}
	return t.Options
}

func (t *TimechartVisualisationConfig) GetQuery() *DatalakeQuery {
	if t == nil {
		return nil
	}
	return t.Query
}
