// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-dashboard/internal/sdk/internal/utils"
)

type VisualisationConfigType string

const (
	VisualisationConfigTypeTimechartVisualisationConfig VisualisationConfigType = "timechartVisualisationConfig"
)

type VisualisationConfig struct {
	TimechartVisualisationConfig *TimechartVisualisationConfig `queryParam:"inline" union:"member"`

	Type VisualisationConfigType
}

func CreateVisualisationConfigTimechartVisualisationConfig(timechartVisualisationConfig TimechartVisualisationConfig) VisualisationConfig {
	typ := VisualisationConfigTypeTimechartVisualisationConfig

	return VisualisationConfig{
		TimechartVisualisationConfig: &timechartVisualisationConfig,
		Type:                         typ,
	}
}

func (u *VisualisationConfig) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var timechartVisualisationConfig TimechartVisualisationConfig = TimechartVisualisationConfig{}
	if err := utils.UnmarshalJSON(data, &timechartVisualisationConfig, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  VisualisationConfigTypeTimechartVisualisationConfig,
			Value: &timechartVisualisationConfig,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for VisualisationConfig", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for VisualisationConfig", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(VisualisationConfigType)
	switch best.Type {
	case VisualisationConfigTypeTimechartVisualisationConfig:
		u.TimechartVisualisationConfig = best.Value.(*TimechartVisualisationConfig)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for VisualisationConfig", string(data))
}

func (u VisualisationConfig) MarshalJSON() ([]byte, error) {
	if u.TimechartVisualisationConfig != nil {
		return utils.MarshalJSON(u.TimechartVisualisationConfig, "", true)
	}

	return nil, errors.New("could not marshal union type VisualisationConfig: all fields are null")
}
