// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type DashboardTile struct {
	Coordinates         *Coordinates         `tfsdk:"coordinates"`
	ID                  types.String         `tfsdk:"id"`
	InsightID           types.String         `tfsdk:"insight_id"`
	Title               types.String         `tfsdk:"title"`
	VisualisationConfig *VisualisationConfig `tfsdk:"visualisation_config"`
	VisualisationID     types.String         `tfsdk:"visualisation_id"`
}
