// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type DatalakeQuery struct {
	AdditionalProperties jsontypes.Normalized              `tfsdk:"additional_properties"`
	Dataset              types.String                      `tfsdk:"dataset"`
	Dimensions           []map[string]jsontypes.Normalized `tfsdk:"dimensions"`
	Filters              []map[string]jsontypes.Normalized `tfsdk:"filters"`
	Measure              types.String                      `tfsdk:"measure"`
}
