// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type OrgAccess struct {
	Any jsontypes.Normalized `queryParam:"inline" tfsdk:"any"`
	One types.String         `queryParam:"inline" tfsdk:"one"`
}
