// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ShareGrant struct {
	Permission types.String `tfsdk:"permission"`
	UserID     types.String `tfsdk:"user_id"`
}
