// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
)

type TimechartVisualisationConfig struct {
	Options map[string]jsontypes.Normalized `tfsdk:"options"`
	Query   *DatalakeQuery                  `tfsdk:"query"`
}
