// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type VisualisationConfig struct {
	TimechartVisualisationConfig *TimechartVisualisationConfig `queryParam:"inline" tfsdk:"timechart_visualisation_config"`
}
